import { utilService } from "../../../services/util.service.js";

export const emails = [
  {
    id: utilService.makeId(),
    subject: "Miss you!",
    body: "Would love to catch up sometimes",
    isRead: false,
    sentAt: Date.now(),
    from: "friendship@horse.com",
    isTrash: false,
    isDraft: false,
    isSent: false,
  },
  {
    id: utilService.makeId(),
    subject: "Paypal Password reset",
    body: utilService.makeLorem(20),
    isRead: true,
    sentAt: 1630105901430,
    from: "service@paypal.com",
    isTrash: false,
    isDraft: false,
    isSent: false,
  },
  {
    id: utilService.makeId(),
    subject: "github acsses aprooved",
    body: utilService.makeLorem(20),
    isRead: false,
    sentAt: 16288105900550,
    to: "Kuki@appsus.com",
    isTrash: false,
    isDraft: false,
    isSent: true,
  },
  {
    id: utilService.makeId(),
    subject: "Are You ready for this weekend?",
    body: utilService.makeLorem(20),
    isRead: false,
    sentAt: 16267105900550,
    to: "Kuki@appsus.com",
    isTrash: false,
    isDraft: true,
    isSent: false,
  },
  {
    id: utilService.makeId(),
    subject: "Its not me Its You !bye",
    body: utilService.makeLorem(20),
    isRead: false,
    sentAt: 16227105900550,
    from: "ex@hell.com",
    isTrash: true,
    isDraft: false,
    isSent: false,
  },
  {
    id: utilService.makeId(),
    subject: "what are u doing today ?",
    body: utilService.makeLorem(20),
    isRead: false,
    sentAt: 1626105901550,
    from: "ex@hell.com",
    isTrash: true,
    isDraft: false,
    isSent: false,
  },
  {
    id: utilService.makeId(),
    subject: "hey can you send me your new address ?",
    body: utilService.makeLorem(20),
    isRead: false,
    sentAt: 1625505901650,
    to: "friend@no.com",
    isTrash: false,
    isDraft: true,
    isSent: false,
  },
  {
    id: utilService.makeId(),
    subject: "I dont have money stop sending emails!",
    body: utilService.makeLorem(20),
    isRead: false,

    sentAt: 1620105901750,
    to: "Asos@gmail.com",
    isTrash: false,
    isDraft: false,
    isSent: true,
  },
  {
    id: utilService.makeId(),
    subject: "Asos 20% OFF ALL SITE!!!",
    body: utilService.makeLorem(20),
    isRead: false,
    sentAt: 1611133930594,
    from: "Asos@gmail.com",
    isTrash: false,
    isDraft: false,
    isSent: false,
  },

  {
    id: utilService.makeId(),
    subject: "You won a 1MILION XRP",
    body: utilService.makeLorem(20),
    isRead: false,
    sentAt: 1551153430594,
    from: "scam@presshere.com",
    isTrash: true,
    isDraft: false,
    isSent: false,
  },
];
